version: "3.9"
services:
  db:
    image: mysql:8
    container_name: todo_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
      MYSQL_USER: app
      MYSQL_PASSWORD: app1234
    ports:
      - "3307:3306"   # 로컬 3307 → 컨테이너 3306
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
